export default {
    ADD_COMMENT:'ADD_COMMENT',
    REMOVE_COMMENT : 'REMOVE_COMMENT',
    EDIT_COMMENT :'EDIT_COMMENT',
    FILTER_POST : 'FILTER_POST',
    RESET_FILTER : 'RESET_FILTER',
    UPDATE_FORM : 'UPDATE_FORM',
    RESET_FORM : 'RESET_FORM'
}